# Site settings
title: Jérémi Robitaille-Brassard
version: "v1"
description: "Jérémi Robitaille-Brassard"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jr-b.net" # the base hostname & protocol for your site
permalink: /blogue/:title/

defaults:
  - scope:
      path: "/images"
    values:
      image: true

# Tachyons Version
tv: "4.6.1"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]

# Gems
plugins:
  - jekyll-seo-tag

# Encoding
encoding: utf-8
